spring.application.name=solve

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XE
spring.datasource.username=system
spring.datasource.password=admin
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

# Logs útiles para detectar errores tipo ORA-17059
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# JWT
# Debe tener al menos 32 bytes en Base64 para HS256.
app.jwt.secret=V1ZWR1JrVm1hVzVqZEdWelpHOWZVMlZqY21WMFh6TXlRbmxrWlhNPQ==
app.jwt.expiration-ms=86400000

# ===============================
# CONFIGURACIÓN DE CORREO SMTP
# EJEMPLO CON GMAIL
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# NO CAMBIAR CORREO NI CONTRASEÑA
spring.mail.username=solve.system10@gmail.com   
spring.mail.password=dnyu cgyu pkll ymdz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
